// next-sitemap.config.js
const districtsArray = [
  'Chittor',
  'East Godavari',
  'Guntur',
  'Barpeta',
  'Cachar',
  'Karbi Anglong',
  'Morigaon',
  'Nalbari',
  'Sibsagar',
  'Kishanganj',
  'Rohtas',
  'Chandigarh',
  'Balod',
  'Balodabazar',
  'Bilaspur',
  'Dantewada',
  'Dhamtari',
  'Durg',
  'Kabirdham',
  'Kanker',
  'Raigarh',
  'Rajnandgaon',
  'Sukma',
  'South Goa',
  'Ahmedabad',
  'Amreli',
  'Anand',
  'Banaskanth',
  'Bharuch',
  'Bhavnagar',
  'Botad',
  'Chhota Udaipur',
  'Dahod',
  'Devbhumi Dwarka',
  'Gandhinagar',
  'Gir Somnath',
  'Jamnagar',
  'Junagarh',
  'Kachchh',
  'Kheda',
  'Mehsana',
  'Morbi',
  'Navsari',
  'Panchmahals',
  'Patan',
  'Porbandar',
  'Rajkot',
  'Sabarkantha',
  'Surat',
  'Surendranagar',
  'Vadodara(Baroda)',
  'Ambala',
  'Faridabad',
  'Fatehabad',
  'Gurgaon',
  'Hissar',
  'Jhajar',
  'Kaithal',
  'Karnal',
  'Kurukshetra',
  'Mahendragarh-Narnaul',
  'Mewat',
  'Panchkula',
  'Panipat',
  'Rewari',
  'Rohtak',
  'Sonipat',
  'Yamuna Nagar',
  'Hamirpur',
  'Kangra',
  'Kullu',
  'Mandi',
  'Shimla',
  'Una',
  'Anantnag',
  'Badgam',
  'Jammu',
  'Kathua',
  'Pulwama',
  'Rajouri',
  'Srinagar',
  'Bangalore',
  'Belgaum',
  'Bellary',
  'Chamrajnagar',
  'Dharwad',
  'Gadag',
  'Kolar',
  'Koppal',
  'Mysore',
  'Raichur',
  'Shimoga',
  'Yadgiri',
  'Alappuzha',
  'Ernakulam',
  'Idukki',
  'Kannur',
  'Kasargod',
  'Kollam',
  'Kottayam',
  'Kozhikode(Calicut)',
  'Malappuram',
  'Palakad',
  'Pathanamthitta',
  'Thirssur',
  'Thiruvananthapuram',
  'Wayanad',
  'Ashoknagar',
  'Badwani',
  'Bhopal',
  'Chhatarpur',
  'Datia',
  'Dewas',
  'Dhar',
  'Gwalior',
  'Harda',
  'Hoshangabad',
  'Indore',
  'Jabalpur',
  'Jhabua',
  'Khandwa',
  'Khargone',
  'Mandla',
  'Mandsaur',
  'Narsinghpur',
  'Neemuch',
  'Raisen',
  'Rajgarh',
  'Ratlam',
  'Sagar',
  'Sehore',
  'Seoni',
  'Sheopur',
  'Sidhi',
  'Ujjain',
  'Umariya',
  'Vidisha',
  'Ahmednagar',
  'Beed',
  'Buldhana',
  'Chandrapur',
  'Chattrapati Sambhajinagar',
  'Hingoli',
  'Jalgaon',
  'Latur',
  'Mumbai',
  'Nagpur',
  'Nashik',
  'Pune',
  'Raigad',
  'Ratnagiri',
  'Sangli',
  'Satara',
  'Sholapur',
  'Thane',
  'Vashim',
  'Bishnupur',
  'Imphal East',
  'Kakching',
  'Thoubal',
  'East Khasi Hills',
  'West Garo Hills',
  'Delhi',
  'Balasore',
  'Dhenkanal',
  'Gajapati',
  'Ganjam',
  'Sundergarh',
  'Amritsar',
  'Bhatinda',
  'Fazilka',
  'Ferozpur',
  'Gurdaspur',
  'Hoshiarpur',
  'Jalandhar',
  'Ludhiana',
  'Mansa',
  'Mohali',
  'Muktsar',
  'Nawanshahr',
  'Patiala',
  'Ropar (Rupnagar)',
  'Sangrur',
  'Tarntaran',
  'Ajmer',
  'Alwar',
  'Balotra',
  'Baran',
  'Bikaner',
  'Bundi',
  'Chittorgarh',
  'Dausa',
  'Dungarpur',
  'Ganganagar',
  'Hanumangarh',
  'Jaipur',
  'Jalore',
  'Jhalawar',
  'Jodhpur',
  'Kota',
  'Pratapgarh',
  'Sikar',
  'Tonk',
  'Ariyalur',
  'Chengalpattu',
  'Coimbatore',
  'Cuddalore',
  'Dharmapuri',
  'Dindigul',
  'Erode',
  'Kallakuruchi',
  'Kancheepuram',
  'Karur',
  'Krishnagiri',
  'Madurai',
  'Nagapattinam',
  'Nagercoil (Kannyiakumari)',
  'Namakkal',
  'Perambalur',
  'Pudukkottai',
  'Ramanathapuram',
  'Ranipet',
  'Salem',
  'Sivaganga',
  'Tenkasi',
  'Thanjavur',
  'The Nilgiris',
  'Theni',
  'Thiruchirappalli',
  'Thirunelveli',
  'Thirupathur',
  'Thirupur',
  'Thiruvannamalai',
  'Thiruvarur',
  'Thiruvellore',
  'Tuticorin',
  'Vellore',
  'Villupuram',
  'Virudhunagar',
  'Adilabad',
  'Hyderabad',
  'Karimnagar',
  'Khammam',
  'Mahbubnagar',
  'Medak',
  'Nalgonda',
  'Ranga Reddy',
  'Warangal',
  'Dhalai',
  'Khowai',
  'North Tripura',
  'South District',
  'Agra',
  'Aligarh',
  'Ambedkarnagar',
  'Amethi',
  'Amroha',
  'Auraiya',
  'Ayodhya',
  'Azamgarh',
  'Badaun',
  'Baghpat',
  'Bahraich',
  'Ballia',
  'Balrampur',
  'Banda',
  'Barabanki',
  'Bareilly',
  'Basti',
  'Bijnor',
  'Bulandshahar',
  'Chandauli',
  'Deoria',
  'Etah',
  'Etawah',
  'Farukhabad',
  'Fatehpur',
  'Firozabad',
  'Gautam Budh Nagar',
  'Ghaziabad',
  'Ghazipur',
  'Gonda',
  'Gorakhpur',
  'Hardoi',
  'Hathras',
  'Jalaun (Orai)',
  'Jaunpur',
  'Jhansi',
  'Kannuj',
  'Kanpur',
  'Kaushambi',
  'Khiri (Lakhimpur)',
  'Kushinagar',
  'Lakhimpur',
  'Lalitpur',
  'Lucknow',
  'Maharajganj',
  'Mahoba',
  'Mainpuri',
  'Mathura',
  'Mau(Maunathbhanjan)',
  'Meerut',
  'Mirzapur',
  'Muzaffarnagar',
  'Pillibhit',
  'Prayagraj',
  'Raebarelli',
  'Saharanpur',
  'Sambhal',
  'Sant Kabir Nagar',
  'Shahjahanpur',
  'Shamli',
  'Siddharth Nagar',
  'Sitapur',
  'Unnao',
  'Dehradoon',
  'Garhwal (Pauri)',
  'Haridwar',
  'Nanital',
  'UdhamSinghNagar',
  'Bankura',
  'Birbhum',
  'Darjeeling',
  'Hooghly',
  'Medinipur(E)',
  'Medinipur(W)',
  'Murshidabad',
  'North 24 Parganas',
  'Nellore',
  'Kamrup',
  'Buxar',
  'Madhubani',
  'Jashpur',
  'Surajpur',
  'Dang',
  'Palwal',
  'Sirsa',
  'Chamba',
  'Davangere',
  'Hassan',
  'Haveri',
  'Alirajpur',
  'Burhanpur',
  'Chhindwara',
  'Dindori',
  'Guna',
  'Morena',
  'Satna',
  'Shajapur',
  'Shivpuri',
  'Dharashiv(Usmanabad)',
  'Kolhapur',
  'Parbhani',
  'Wardha',
  'Yavatmal',
  'Imphal West',
  'Wokha',
  'Pondicherry',
  'Faridkot',
  'Moga',
  'Jhunjhunu',
  'Jaipur Rural',
  'Jodhpur Rural',
  'Udaipur',
  'Nizamabad',
  'Gomati',
  'Rampur',
  'Champawat',
  'Visakhapatnam',
];

module.exports = {
  siteUrl: 'https://mandiprices.in',
  generateRobotsTxt: true,
  sitemapSize: 7000,
  additionalPaths: async (config) => {
    return districtsArray.map((district) => ({
      loc: `/markets/${encodeURIComponent(district)}`,
      lastmod: new Date().toISOString(),
      changefreq: 'monthly',
      priority: 0.8,
    }));
  },
};
