export const districtsArray = [
  'Chittor',
  'East Godavari',
  'Guntur',
  'Barpeta',
  'Cachar',
  'Karbi Anglong',
  'Morigaon',
  'Nalbari',
  'Sibsagar',
  'Kishanganj',
  'Rohtas',
  'Chandigarh',
  'Balod',
  'Balodabazar',
  'Bilaspur',
  'Dantewada',
  'Dhamtari',
  'Durg',
  'Kabirdham',
  'Kanker',
  'Raigarh',
  'Rajnandgaon',
  'Sukma',
  'South Goa',
  'Ahmedabad',
  'Amreli',
  'Anand',
  'Banaskanth',
  'Bharuch',
  'Bhavnagar',
  'Botad',
  'Chhota Udaipur',
  'Dahod',
  'Devbhumi Dwarka',
  'Gandhinagar',
  'Gir Somnath',
  'Jamnagar',
  'Junagarh',
  'Kachchh',
  'Kheda',
  'Mehsana',
  'Morbi',
  'Navsari',
  'Panchmahals',
  'Patan',
  'Porbandar',
  'Rajkot',
  'Sabarkantha',
  'Surat',
  'Surendranagar',
  'Vadodara(Baroda)',
  'Ambala',
  'Faridabad',
  'Fatehabad',
  'Gurgaon',
  'Hissar',
  'Jhajar',
  'Kaithal',
  'Karnal',
  'Kurukshetra',
  'Mahendragarh-Narnaul',
  'Mewat',
  'Panchkula',
  'Panipat',
  'Rewari',
  'Rohtak',
  'Sonipat',
  'Yamuna Nagar',
  'Hamirpur',
  'Kangra',
  'Kullu',
  'Mandi',
  'Shimla',
  'Una',
  'Anantnag',
  'Badgam',
  'Jammu',
  'Kathua',
  'Pulwama',
  'Rajouri',
  'Srinagar',
  'Bangalore',
  'Belgaum',
  'Bellary',
  'Chamrajnagar',
  'Dharwad',
  'Gadag',
  'Kolar',
  'Koppal',
  'Mysore',
  'Raichur',
  'Shimoga',
  'Yadgiri',
  'Alappuzha',
  'Ernakulam',
  'Idukki',
  'Kannur',
  'Kasargod',
  'Kollam',
  'Kottayam',
  'Kozhikode(Calicut)',
  'Malappuram',
  'Palakad',
  'Pathanamthitta',
  'Thirssur',
  'Thiruvananthapuram',
  'Wayanad',
  'Ashoknagar',
  'Badwani',
  'Bhopal',
  'Chhatarpur',
  'Datia',
  'Dewas',
  'Dhar',
  'Gwalior',
  'Harda',
  'Hoshangabad',
  'Indore',
  'Jabalpur',
  'Jhabua',
  'Khandwa',
  'Khargone',
  'Mandla',
  'Mandsaur',
  'Narsinghpur',
  'Neemuch',
  'Raisen',
  'Rajgarh',
  'Ratlam',
  'Sagar',
  'Sehore',
  'Seoni',
  'Sheopur',
  'Sidhi',
  'Ujjain',
  'Umariya',
  'Vidisha',
  'Ahmednagar',
  'Beed',
  'Buldhana',
  'Chandrapur',
  'Chattrapati Sambhajinagar',
  'Hingoli',
  'Jalgaon',
  'Latur',
  'Mumbai',
  'Nagpur',
  'Nashik',
  'Pune',
  'Raigad',
  'Ratnagiri',
  'Sangli',
  'Satara',
  'Sholapur',
  'Thane',
  'Vashim',
  'Bishnupur',
  'Imphal East',
  'Kakching',
  'Thoubal',
  'East Khasi Hills',
  'West Garo Hills',
  'Delhi',
  'Balasore',
  'Dhenkanal',
  'Gajapati',
  'Ganjam',
  'Sundergarh',
  'Amritsar',
  'Bhatinda',
  'Fazilka',
  'Ferozpur',
  'Gurdaspur',
  'Hoshiarpur',
  'Jalandhar',
  'Ludhiana',
  'Mansa',
  'Mohali',
  'Muktsar',
  'Nawanshahr',
  'Patiala',
  'Ropar (Rupnagar)',
  'Sangrur',
  'Tarntaran',
  'Ajmer',
  'Alwar',
  'Balotra',
  'Baran',
  'Bikaner',
  'Bundi',
  'Chittorgarh',
  'Dausa',
  'Dungarpur',
  'Ganganagar',
  'Hanumangarh',
  'Jaipur',
  'Jalore',
  'Jhalawar',
  'Jodhpur',
  'Kota',
  'Pratapgarh',
  'Sikar',
  'Tonk',
  'Ariyalur',
  'Chengalpattu',
  'Coimbatore',
  'Cuddalore',
  'Dharmapuri',
  'Dindigul',
  'Erode',
  'Kallakuruchi',
  'Kancheepuram',
  'Karur',
  'Krishnagiri',
  'Madurai',
  'Nagapattinam',
  'Nagercoil (Kannyiakumari)',
  'Namakkal',
  'Perambalur',
  'Pudukkottai',
  'Ramanathapuram',
  'Ranipet',
  'Salem',
  'Sivaganga',
  'Tenkasi',
  'Thanjavur',
  'The Nilgiris',
  'Theni',
  'Thiruchirappalli',
  'Thirunelveli',
  'Thirupathur',
  'Thirupur',
  'Thiruvannamalai',
  'Thiruvarur',
  'Thiruvellore',
  'Tuticorin',
  'Vellore',
  'Villupuram',
  'Virudhunagar',
  'Adilabad',
  'Hyderabad',
  'Karimnagar',
  'Khammam',
  'Mahbubnagar',
  'Medak',
  'Nalgonda',
  'Ranga Reddy',
  'Warangal',
  'Dhalai',
  'Khowai',
  'North Tripura',
  'South District',
  'Agra',
  'Aligarh',
  'Ambedkarnagar',
  'Amethi',
  'Amroha',
  'Auraiya',
  'Ayodhya',
  'Azamgarh',
  'Badaun',
  'Baghpat',
  'Bahraich',
  'Ballia',
  'Balrampur',
  'Banda',
  'Barabanki',
  'Bareilly',
  'Basti',
  'Bijnor',
  'Bulandshahar',
  'Chandauli',
  'Deoria',
  'Etah',
  'Etawah',
  'Farukhabad',
  'Fatehpur',
  'Firozabad',
  'Gautam Budh Nagar',
  'Ghaziabad',
  'Ghazipur',
  'Gonda',
  'Gorakhpur',
  'Hardoi',
  'Hathras',
  'Jalaun (Orai)',
  'Jaunpur',
  'Jhansi',
  'Kannuj',
  'Kanpur',
  'Kaushambi',
  'Khiri (Lakhimpur)',
  'Kushinagar',
  'Lakhimpur',
  'Lalitpur',
  'Lucknow',
  'Maharajganj',
  'Mahoba',
  'Mainpuri',
  'Mathura',
  'Mau(Maunathbhanjan)',
  'Meerut',
  'Mirzapur',
  'Muzaffarnagar',
  'Pillibhit',
  'Prayagraj',
  'Raebarelli',
  'Saharanpur',
  'Sambhal',
  'Sant Kabir Nagar',
  'Shahjahanpur',
  'Shamli',
  'Siddharth Nagar',
  'Sitapur',
  'Unnao',
  'Dehradoon',
  'Garhwal (Pauri)',
  'Haridwar',
  'Nanital',
  'UdhamSinghNagar',
  'Bankura',
  'Birbhum',
  'Darjeeling',
  'Hooghly',
  'Medinipur(E)',
  'Medinipur(W)',
  'Murshidabad',
  'North 24 Parganas',
  'Nellore',
  'Kamrup',
  'Buxar',
  'Madhubani',
  'Jashpur',
  'Surajpur',
  'Dang',
  'Palwal',
  'Sirsa',
  'Chamba',
  'Davangere',
  'Hassan',
  'Haveri',
  'Alirajpur',
  'Burhanpur',
  'Chhindwara',
  'Dindori',
  'Guna',
  'Morena',
  'Satna',
  'Shajapur',
  'Shivpuri',
  'Dharashiv(Usmanabad)',
  'Kolhapur',
  'Parbhani',
  'Wardha',
  'Yavatmal',
  'Imphal West',
  'Wokha',
  'Pondicherry',
  'Faridkot',
  'Moga',
  'Jhunjhunu',
  'Jaipur Rural',
  'Jodhpur Rural',
  'Udaipur',
  'Nizamabad',
  'Gomati',
  'Rampur',
  'Champawat',
  'Visakhapatnam',
];

export const statesArray = [
  'Andhra Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Nagaland',
  'NCT of Delhi',
  'Odisha',
  'Pondicherry',
  'Punjab',
  'Rajasthan',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttrakhand',
  'West Bengal',
];

export const marketsArray = [
  'Palamaner',
  'Rajahmundry',
  'Ravulapelem',
  'Pidugurala(Palnadu)',
  'Barpeta Road',
  'Sonabarighat',
  'Diphu',
  'Burhagaon',
  'Nalbari',
  'Sibsagar',
  'Bahadurganj',
  'Sasaram',
  'Chandigarh(Grain/Fruit)',
  'Dondi',
  'Bhatgaon',
  'Tiphra',
  'Gidam',
  'Belarbahara',
  'Kurud',
  'Durg',
  'Kawardha',
  'Narharpur',
  'Raigarh',
  'Rajnandgaon',
  'Kukanar',
  'Curchorem',
  'Mandal',
  'Amreli',
  'Babra',
  'Damnagar',
  'Anand(Veg',
  'Borsad',
  'Umreth',
  'Bhabhar',
  'Deesa(Bhildi)',
  'Dhanera',
  'Palanpur',
  'Thara',
  'Thara(Shihori)',
  'Ankleshwar',
  'Jambusar',
  'Bhavnagar',
  'Mahuva(Station Road)',
  'Botad',
  'Bodeliu',
  'Dahod',
  'Dahod(Veg. Market)',
  'Davgadbaria(Piplod)',
  'Limkheda',
  'Zalod(Zalod)',
  'Bhanvad',
  'Dehgam(Rekhiyal)',
  'Kalol(Veg',
  'Mansa',
  'Mansa(Manas Veg Yard)',
  'Veraval',
  'Dhrol',
  'Jamnagar',
  'Kalawad',
  'Bhesan',
  'Junagadh',
  'Mangrol',
  'Visavadar',
  'Bhuj',
  'Nadiyad(Chaklasi)',
  'Nadiyad(Piplag)',
  'Kadi',
  'Mehsana',
  'Mehsana(Jornang)',
  'Mehsana(Mehsana Veg)',
  'Unjha',
  'Vijapur',
  'Morbi',
  'Vankaner',
  'Bilimora',
  'Navsari',
  'Gogamba',
  'Morva Hafad',
  'Harij',
  'Patan',
  'Radhanpur',
  'Siddhpur',
  'Porbandar',
  'Dhoraji',
  'Gondal(Veg.market Gondal)',
  'Jasdan',
  'Jetpur(Dist.Rajkot)',
  'Rajkot',
  'Rajkot(Veg.Sub Yard)',
  'Upleta',
  'Dhansura',
  'Talod',
  'Vadali',
  'Nizar(Kukarmuda)',
  'Nizar(Pumkitalov)',
  'Surat',
  'Dasada Patadi',
  'Vadhvan',
  'Padra',
  'Barara',
  'Naraingarh',
  'Shahzadpur',
  'Ballabhgarh',
  'Faridabad',
  'Jakhal',
  'Gurgaon',
  'Barwala(Hisar)',
  'Hansi',
  'Hissar',
  'Uklana',
  'Jhajjar',
  'Dhand',
  'Gharaunda',
  'Ladwa',
  'Pehowa',
  'Shahabad',
  'Mohindergarh',
  'Narnaul',
  'FerozpurZirkha(Nagina)',
  'Nuh',
  'Punhana',
  'Barwala',
  'New Grain Market',
  'Madlauda',
  'Panipat',
  'Rewari',
  'Meham',
  'Rohtak',
  'Ganaur',
  'Gohana',
  'Chhachrauli',
  'Jagadhri',
  'Mustafabad',
  'Radaur',
  'Sadhaura',
  'Bilaspur',
  'Hamirpur',
  'Hamirpur(Nadaun)',
  'Kangra',
  'Kangra(Baijnath)',
  'Kangra(Jaisinghpur)',
  'Kangra(Nagrota Bagwan)',
  'Palampur',
  'Bandrol',
  'Bhuntar',
  'Kullu',
  'Kullu(Chauri Bihal)',
  'Dhanotu (Mandi)',
  'Mandi(Mandi)',
  'Mandi(Takoli)',
  'Rohroo',
  'Shimla',
  'Santoshgarh',
  'Una',
  'Ashahipora (Anantnagh)',
  'Kulgam',
  'Zaloosa-Chararishrief (F&V)',
  'Akhnoor',
  'Narwal Jammu (F&V)',
  'Kathua',
  'Pulwama (F&V)',
  'Shopian',
  'Rajouri (F&V)',
  'Ganderbal',
  'Parimpore',
  'Bangalore',
  'Binny Mill (F&V)',
  'Ramanagara',
  'Sankeshwar',
  'Kottur',
  'Chamaraj Nagar',
  'Gundlupet',
  'Hubli (Amaragol)',
  'Kalagategi',
  'Laxmeshwar',
  'Chintamani',
  'Gowribidanoor',
  'Malur',
  'Kustagi',
  'K.R.Nagar',
  'Mysore (Bandipalya)',
  'Santhesargur',
  'Lingasugur',
  'Shimoga',
  'Yadgir',
  'Cheriyanadu  VFPCK',
  'Cherthala',
  'Harippad',
  'Kayamkulam',
  'Pandanadu  VFPCK',
  'Thazhakkara  VFPCK',
  'Angamaly',
  'North Paravur',
  'Perumbavoor',
  'Piravam',
  'Puthenvelikkara  VFPCK',
  'Thiruvaniyoor  VFPCK',
  'Adimali',
  'Thodupuzha',
  'Payyannur',
  'Taliparamba',
  'Kanjangadu',
  'Manjeswaram',
  'Neeleswaram',
  'Anchal',
  'Chathanoor',
  'Kadakkal  VFPCK',
  'Kollam',
  'Kottarakkara',
  'Athirampuzha',
  'Ettumanoor',
  'Kanjirappally',
  'Kottayam',
  'Kuruppanthura',
  'Pampady',
  'Thalayolaparambu',
  'Kallachi',
  'Mukkom',
  'Palayam',
  'Perambra',
  'Quilandy',
  'Vengeri(Kozhikode)',
  'Elamkur  VFPCK',
  'Kottakkal',
  'Thirurrangadi',
  'Elevancheri VFPCK',
  'Koduvayoor',
  'Kollengode',
  'Palakkad',
  'Pattambi',
  'Vadakkenchery',
  'Kalanjoor  VFPCK',
  'Kuttoor',
  'Mezhuveli  VFPCK',
  'Pramadom VFPCK',
  'Ranniangadi',
  'Chavakkad',
  'Chelakkara',
  'Marottichal  VFPCK',
  'Muriyad  VFPCK',
  'Puthur  VFPCK',
  'Thrissur',
  'Attingal',
  'Chala',
  'Maranelloor VFPCK',
  'Nedumangadu',
  'Parassala',
  'Pothencode',
  'Kalpetta',
  'Pulpally',
  'Ashoknagar',
  'Anjad',
  'Badwani',
  'Badwani(F&V)',
  'Khetia',
  'Sendhwa(F&V)',
  'Berasia',
  'Bhopal',
  'Badamalhera',
  'Chattarpur(F&V)',
  'LavKush Nagar(Laundi)',
  'Naugaon',
  'Bhander',
  'Haatpipliya',
  'Dhar',
  'Manawar',
  'Dabra',
  'Lashkar',
  'Timarni(F&V)',
  'Itarsi',
  'Pipariya',
  'Pipariya(F&V)',
  'Gautampura',
  'Jabalpur',
  'Petlawad',
  'Khandwa',
  'Sanawad(F&V)',
  'Bedia',
  'Bhikangaon',
  'Khargone',
  'Sanawad',
  'Bichhiya',
  'Mandsaur',
  'Piplya',
  'Shamgarh',
  'Tendukheda',
  'Manasa',
  'Neemuch',
  'Bareli',
  'Silvani',
  'Sarangpur(F&V)',
  'Jaora',
  'Deori',
  'Nasrullaganj',
  'Sehore',
  'Seoni',
  'Sheopurkalan(F&V)',
  'Sidhi',
  'Singrauli(F&V)',
  'Singrauli',
  'Sirmour',
  'Chhapara',
  'Balaghat',
  'Katangi',
  'Malajkhand',
  'Waraseoni',
  'Satna',
  'Nagod(F&V)',
  'Sihora',
  'Chanderi',
  'Dabra',
  'Chanderi',
  'Ratlam',
  'Badnagar',
  'Khacharod',
  'Bajna',
  'Rajgarh',
  'Bioara',
  'Sironj',
  'Biaora(F&V)',
  'Vidisha',
  'Akola',
  'Telhara',
  'Sindkhedraja',
  'Chandurbazar',
  'Chandur Railway',
  'Ghugus',
  'Jalgaon',
  'Nashik',
  'Aurangabad',
  'Wardha',
];

export const commoditiesArray = [
  'Green Chilli',
  'Potato',
  'Paddy(Dhan)(Common)',
  'Banana',
  'Dry Chillies',
  'Capsicum',
  'Tomato',
  'Cabbage',
  'Bhindi(Ladies Finger)',
  'Cauliflower',
  'Bitter gourd',
  'Brinjal',
  'Pumpkin',
  'Onion',
  'Bottle gourd',
  'Cucumbar(Kheera)',
  'Beetroot',
  'Little gourd (Kundru)',
  'Green Peas',
  'Apple',
  'Coriander(Leaves)',
  'Guava',
  'Methi(Leaves)',
  'Tinda',
  'Groundnut',
  'Arecanut(Betelnut/Supari)',
  'Cummin Seed(Jeera)',
  'Arhar (Tur/Red Gram)(Whole)',
  'Green Gram (Moong)(Whole)',
  'Jowar(Sorghum)',
  'Sesamum(Sesame',
  'Ginger(Green)',
  'Yard',
  'Bajra(Pearl Millet/Cumbu)',
  'Castor Seed',
  'Mustard',
  'Rajgir',
  'Wheat',
  'Cotton',
  'Soyabean',
  'Maize',
  'Bengal Gram(Gram)(Whole)',
  'Market',
  'Guar Seed(Cluster Beans Seed)',
  'Lemon',
  'Ajwan',
  'Black Gram (Urd Beans)(Whole)',
  'Corriander seed',
  'Soanf',
  'Beans',
  'Ground Nut Seed',
  'Drumstick',
  'French Beans (Frasbean)',
  'Guar',
  'Colacasia',
  'Carrot',
  'Peas Wet',
  'Pomegranate',
  'Water Melon',
  'Orange',
  'Raddish',
  'Pineapple',
  'Garlic',
  'Ginger(Dry)',
  'Mousambi(Sweet Lime)',
  'Panchkula',
  'Ridgeguard(Tori)',
  'Spinach',
  'Squash(Chappal Kadoo)',
  'Papaya',
  'Indian Colza(Sarson)',
  'Persimon(Japani Fal)',
  'Sponge gourd',
  'Pear(Marasebu)',
  'Indian Beans (Seam)',
  'Grapes',
  'Arhar Dal(Tur Dal)',
  'Bengal Gram Dal (Chana Dal)',
  'Green Gram Dal (Moong Dal)',
  'Ragi (Finger Millet)',
  'Bangalore',
  'Ashgourd',
  'Green Avare (W)',
  'Rice',
  'Sunflower',
  'Turmeric',
  'Safflower',
  'Seemebadnekai',
  'Sweet Pumpkin',
  'Black Gram Dal (Urd Dal)',
  'Snakeguard',
  'Amaranthus',
  'Amphophalus',
  'Banana - Green',
  'Cowpea(Veg)',
  'Mango (Raw-Ripe)',
  'Tapioca',
  'Elephant Yam (Suran)',
  'Coconut',
  'Coconut Seed',
  'Copra',
  'Long Melon(Kakri)',
  'Mango',
  'Lime',
  'Sweet Potato',
  'Chili Red',
  'Cluster beans',
  'Black pepper',
  'Rubber',
  'Yam (Ratalu)',
  'Lentil (Masur)(Whole)',
  'Neem Seed',
  'Kabuli Chana(Chickpeas-White)',
  'Chilly Capsicum',
  'Seetapal',
  'Gur(Jaggery)',
  'Masur Dal',
  'Chikoos(Sapota)',
  'Cow',
  'Onion Green',
  'Bhajipura Market)',
  'Jack Fruit',
  'Karbuja(Musk Melon)',
  'Mashrooms',
  'Pointed gourd (Parval)',
  'Ramphal',
  'Season Leaves',
  'Kinnow',
  'Moath Dal',
  'Mint(Pudina)',
  'Tender Coconut',
  'Barley (Jau)',
  'Round gourd',
  'Tamarind Fruit',
  'Thondekai',
  'Knool Khol',
  'Turnip',
  'Fig(Anjura/Anjeer)',
  'Amla(Nelli Kai)',
  'Chow Chow',
  'Custard Apple (Sharifa)',
  'Betal Leaves',
  'Tube Flower',
  'Tube Rose(Loose)',
  'Rose(Local)',
  'Jasmine',
  'Kakada',
  'Marigold(Calcutta)',
  'Leafy Vegetable',
  'Ghee',
  'Mustard Oil',
  'Wood',
  'Paddy(Dhan)(Basmati)',
  'White Peas',
  'Firewood',
  'Sugar',
  'Marigold(loose)',
  'Papaya (Raw)',
  'Mahua',
  'Suva (Dill Seed)',
  'Pegeon Pea (Arhar Fali)',
  'Millets',
  'Isabgul (Psyllium)',
  'Peas cod',
  'Lotus Sticks',
  'Chennangi Dal',
  'Foxtail Millet(Navane)',
  'Thogrikai',
  'Kulthi(Horse Gram)',
  'Alsandikai',
  'Cardamoms',
  'Cowpea (Lobia/Karamani)',
  'Linseed',
  'Methi Seeds',
  'Toria',
  'Ox',
  'Peas(Dry)',
  'Groundnut (Split)',
  'Turmeric (raw)',
  'Field Pea',
  'Nutmeg',
  'Coconut Oil',
  'Coffee',
  'Buttery',
  'Kutki',
  'Sabu Dan',
  'Plum',
  'Rose(Loose)',
  'Cherry',
  'Bull',
  'Jute',
  'Red Gram',
  'Kodo Millet(Varagu)',
  'Kartali (Kantola)',
  'Ber(Zizyphus/Borehannu)',
  'Walnut',
  'Alasande Gram',
  'Bunch Beans',
  'Suvarna Gadde',
  'Cloves',
  'Pepper garbled',
  'Pepper ungarbled',
  'Groundnut pods (raw)',
  'Cinamon(Dalchini)',
  'Chakotha',
  'Fish',
  'Cotton Seed',
  'Surat Beans (Papadi)',
  'Avare Dal',
  'Mataki',
  'Duster Beans',
  'Nigella seeds',
  'Almond(Badam)',
  'Cashewnuts',
];

export const varietiesArray = [
  'Green Chilly',
  'Red Nanital',
  'Paddy',
  'Karpura',
  'Red',
  'Capsicum',
  'Tomato',
  'Cabbage',
  'Bhindi',
  'Cauliflower',
  'Bitter Gourd',
  'Brinjal',
  'Pumpkin',
  'Jyoti',
  'Medium',
  'Other',
  'I.R. 64',
  'Beetroot',
  'Little gourd (Kundru)',
  'I.R. 36',
  'Swarna Masuri (OLD)',
  'Apple',
  'Bottle Gourd',
  'Round/Long',
  'Coriander',
  'Guava Navalur',
  'Methi',
  'Tinda',
  'Local',
  'Paddy Coarse',
  'White',
  'Hybrid',
  'Big (With Shell)',
  'Jowar (White)',
  'Gingelly',
  'Green Ginger',
  'Anand',
  'Deshi',
  'Castor seed',
  'G20',
  'Mustard',
  'Rajgir',
  'RCH-2',
  'Shanker 6 (B) 30mm Fine',
  'Soyabean',
  'Potato',
  'Common',
  'Lokwan',
  'Kalol',
  'Split',
  'Black',
  'Bold',
  'Coriander Seed',
  'Lok-1',
  'Whole',
  'Small',
  'Caster',
  'Onion',
  'Ajwan',
  'Black Gram (Whole)',
  'Balli/Habbu',
  'Soanf',
  'Arkasheela Mattigulla',
  'Cummin Seed(Jeera)',
  'Guava',
  'H.B (Unginned)',
  'Ground Nut Seed',
  'A-1',
  'Gwar',
  'Pomogranate',
  'Water Melon',
  'Guava Alahabad',
  'Lemon',
  'Pine Apple',
  'Garlic',
  'Vegitable-fresh',
  'Ridgeguard(Tori)',
  'Banana - Ripe',
  'French Beans (Frasbean)',
  'Kullu Royal Delicious',
  'Indian Colza(Sarson)',
  'Colacasia',
  'Carrot',
  'Persimon(Japani Fal)',
  'American',
  'Delicious',
  'Nagpuri',
  'Spinach',
  'Arhar Dal(Tur)',
  'Bengal Gram Dal',
  'Green Gram Dal',
  'Bangalore-Samall',
  'Fine',
  'Orange',
  'Ashgourd',
  'Cucumbar',
  'Green Avare (W)',
  'Raddish',
  'Hybrid/Local',
  'Gejje',
  'Safflower',
  'Beans (Whole)',
  'Drumstick',
  'Seemebadanekai',
  'Sweet Pumpkin',
  'Black Gram Dal',
  'Green (Whole)',
  'Super Fine',
  'Snakeguard',
  'Big',
  'Palayamthodan',
  'Banana - Green',
  'Cowpea (Veg)',
  'Amaranthus',
  'Average',
  'Indian Beans (Seam)',
  'Mango - Raw-Ripe',
  'Nendra Bale',
  'Amphophalus',
  'Poovan',
  'Coconut Seed',
  'Elephant Yam (Suran)',
  'Red Banana',
  'Robusta',
  'Coconut',
  'Tapioca',
  'Without Ginned Cotton',
  'Yellow',
  'Round',
  'Mill Quality',
  'Wheat',
  'Basmati 1509',
  'Dhan',
  'Cholai Bhaji',
  'Green gram',
  'Gram',
  'Urda/Urd',
  'Soybean-Organic',
  'Masur Dal',
  'Neem leaves',
  'Basumathi',
  'Dollar Gram',
  'Sharbati',
  'Seetapal',
  '1st Sort',
  'Desi (Whole)',
  'Dry Chillies',
  'Jack Fruit',
  'Karbhuja',
  'Mashrooms',
  'Pointed gourd (Parval)',
  'Organic',
  'Kinnow',
  'Moath (W)',
  'Tender Coconut',
  'African Sarson',
  'Big 100 Kg',
  'Onion Green',
  'Avare (W)',
  'Bellary',
  'I Sort',
  'Mint(Pudina)',
  'Tamarind Fruit',
  'Cluster Beans',
  'Thondekai',
  'Knool Khol',
  'Papaya',
  'Hosur Red',
  'Pusakesar',
  'Deshi Red',
  'Turnip',
  'Gouard',
  'Anjura',
  'Darjeeling',
  'Amla',
  'Ranchi',
  'Yam (Ratalu)',
  'Besrai',
  'Chow Chow',
  'Green Peas',
  'Sapota',
  'Annabesahai',
  'Custard Apple(Sharifa)',
  'Mysore',
  'Lime',
  'Tube Flower',
  'Tube Rose (Loose)',
  'Rose (Local)',
  'Jasmine',
  'Mousambi',
  'Pears',
  'Kakada',
  'Marigold(Calcutta)',
  'Arhar (Whole)',
  'Safeda',
  'ADT 37',
  'Simla',
  'Big/Thick',
  'Chapathi',
  'Samba Masuri',
  '1001',
  'Leafy Vegetables',
  'Champa',
  'Nasik',
  'Dara',
  'Desi',
  'Ghee',
  'III',
  'Badshah',
  'Mustard Oil',
  'Lohi Black',
  'Kasmir/Shimla - II',
  'Average (Whole)',
  'Pathari',
  'Laha(Sarsib)',
  'Dusheri',
  'White Peas',
  'Sponge gourd',
  'Eucalyptus',
  'Khandsari',
  'U.P. (Split)',
  'Pusa-Red',
  'Milled',
  'Sarson(Black)',
  'Masoor Gola',
  '1009 Kar',
  'Firewood',
  'Chini',
  '1121',
  'Sonalika',
  'Marigold(Loose)',
  'Finger',
  'NO 2',
  'Desi(Bontha)',
  'Bulb',
  'Gulbarga Phatka New',
  'Kalyan',
  'Paddy fine',
  'Sweet Potato',
  'Millets',
  'Pigeon Pea (Arhar Fali)',
  'Isabgul (Psyllium)',
  'Suva (Dill Seed)',
  'G. R. 11',
  'Medium Fine',
  'Milbar',
  'Peas cod',
  'Lotus Sticks',
  'Chennangi Dal',
  'Grade-I',
  'Byadgi',
  'Puna',
  'Thogarikai',
  'Rashi',
  'Grade-III',
  'GCH',
  'Chilly Capsicum',
  'Horse gram (Whole)',
  'Alsandikai',
  'Hosur Green',
  'Supari',
  'Mataa Parboiled',
  'Cowpea (Whole)',
  'Kabuli Chana(Chickpeas-white)',
  'Rasakathai',
  'Desi (F.A.Q. Split)',
  'Linseed-Organic',
  'Pea',
  'Methiseeds',
  'Sujata',
  'Maharashtra 2189',
  'Dry',
  'Golden',
  '999',
  'White (SAFED)',
  'Farmi',
  'B P T',
  'Cotton (Unginned)',
  '2nd Sort',
  'MTU-1010',
  'Coarse',
  'Amruthapani',
  'Red Gold',
  'Kufri Megha',
  'Bengal Gram (Split)',
  'Haldwani',
  'Kala Masoor New',
  'Achhu',
  'Peas(Dry)',
  'Papaya (Raw)',
  'NO 1',
  'Groundnut(Split)',
  '777 New Ind',
  'Rajkot T-9',
  'Deshi White',
  '2189 No. 1',
  'JL-24',
  'Shanker 4 31mm Fine',
  'Peas Wet',
  'Field Pea',
  'Moath Dal',
  'Jawari/Local',
  'Paddy Medium',
  'Garbled',
  'Green Gram Dhall-I',
  'Copra Oil',
  'Barley',
  'Buttery',
  'Kutki',
  'Wheat Mix',
  'Isabgol',
  'Kutki/gnat',
  'Bansi',
  'Pomegranate',
  'Plum',
  'Rose(Loose)',
  '147 Average',
  'Ball',
  'Bull',
  'Local (Whole)',
  'UP',
  'Annigeri',
  'Fine(Basmati)',
  'TD-5',
  'Swarna Masuri (New)',
  'Bhushavali(Pacha)',
  'NO 3',
  'Masuri (W-S)',
  'Rajasthan Tukdi',
  'Lokwan Gujrat',
  'H.Y.4 (Unginned)',
  '2189 No. 2',
  'Narma BT Cotton',
  'Hybrid Red (Cattle Feed)',
  'Banana',
  'Squash(Chappal Kadoo)',
  'Alasande Gram',
  'Mudde',
  'Kaddi',
  'Bunch Beans',
  'Malabar',
  'Kurikatu',
  'Suvarnagadde',
  'Chips',
  'Ungrabled',
  'RSS-4',
  'Copra',
  'Millet',
  'Flaxseed',
  'Puspa (MR 301)',
  'Mahua',
  'Groundnut pods (raw)',
  'Mogan Medium',
  'Chakootha',
  'White Ponni',
  'Ber(Zizyphus)',
  'Cow',
  'Katla(Big)',
  'Rahu(Andhra)',
  'Kartali (Kantola)',
  'Masuri',
  'Sarvati',
  'F.A.Q.',
  'Chandermukhi',
  'Royal Delicious',
  'Desi(Whole)',
  'Chakkarakeli(Red)',
  'Chakkarakeli(White)',
  'Casuarina',
  'MTU-1001',
  'Cotton Seed',
  'Fenugreek-Organic',
  'Full Green',
  'Jowar (Yellow)',
  'Green',
  'Walnut',
  'Avare (Whole)',
  'Guntur',
  'Dappa',
  'Jowar Hybrid',
  'Varalakshmi (Ginned)',
  'Mataki (W)',
  'Sunflower',
  'IR-8',
  'Chana Kabuli',
  'Kalonji/Nigella',
  'White Fozi',
  'Round gourd',
  'Ankola',
  'Red June',
  'F.A.Q',
  'Kabul Small',
];
